# Site settings
title: Love Memory with Freida
email: your-email@domain.com
url: https://ludanlovefang.github.io
description: ""
favicon: "/img/favicon.ico"
lines: # You can add HTML Tags in the Text
  - text: "I AM HERE! Honey!"
  - text: "LUDAN!LUDAN!"
# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#81F7F3'
  links: '#219ab3'

# Footer settings
footer: Shawn

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
